name: Build kubeflow base image

on:
  release:
    types: [published]

env:
  IMAGE_JUPYTERLAB: navikt/kubeflow-dataverk-jupyterlab
  IMAGE_JUPYTERHUB: navikt/kubeflow-dataverk-jupyterhub
  IMAGE_PIPELINES: navikt/kubeflow-dataverk-pipeline
  IMAGE_LOCAL: navikt/kubeflow-dataverk-local

jobs:
  build-jupyterlab-image:
    name: Build jupyterlab docker image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/jupyterlab')
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create tag
        run: echo ::set-env name=IMAGE_TAG::$(date +%Y-%m-%d)--$(git describe --tags)
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build jupyterlab base docker image
        run: docker build -t ${IMAGE_JUPYTERLAB}:${IMAGE_TAG} -f notebooks/jupyterlab/kubeflow/Dockerfile.jupyterlab .
      - name: Login Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push jupyterlab base docker image
        run: docker push ${IMAGE_JUPYTERLAB}:${IMAGE_TAG}

  build-jupyterhub-image:
    name: Build jupyterhub docker image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/jupyterhub')
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create tag
        run: echo ::set-env name=IMAGE_TAG::$(date +%Y-%m-%d)--$(git describe --tags)
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build jupyterhub base docker image
        run: docker build -t ${IMAGE_JUPYTERHUB}:${IMAGE_TAG} -f notebooks/jupyterhub/Dockerfile.jupyterhub .
      - name: Login Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push jupyterhub base docker image
        run: docker push ${IMAGE_JUPYTERHUB}:${IMAGE_TAG}

  build-pipeline-image:
    name: Build kubeflow pipeline docker image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/pipeline')
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create tag
        run: echo ::set-env name=IMAGE_TAG::$(date +%Y-%m-%d)--$(git describe --tags)
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build pipeline base docker image
        run: docker build -t ${IMAGE_PIPELINES}:${IMAGE_TAG} -f pipelines/Dockerfile.pipelines .
      - name: Login Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push pipeline base docker image
        run: docker push ${IMAGE_PIPELINES}:${IMAGE_TAG}

  build-jupyterlab-local-image:
    name: Build jupyterlab local image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/local')
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Create tag
      run: echo ::set-env name=IMAGE_TAG::$(date +%Y-%m-%d)--$(git describe --tags)
    - name: Login to Github package registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
    - name: Build pipeline base docker image
      run: docker build -t ${IMAGE_LOCAL}:${IMAGE_TAG} -f jupyterlab/local/Dockerfile.jupyterlab.local .
    - name: Login Dockerhub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push pipeline base docker image
      run: docker push ${IMAGE_LOCAL}:${IMAGE_TAG}
