name: build

on:
  release:
    types: [published]
    tags-ignore:
      - 'jh*'
      - 'jl*'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/kubeflow-dataverk-pipelines

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create tag
        run: echo ::set-env name=IMAGE_TAG::$(git describe --tags)
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build pipeline docker image
        run: docker build -t ${IMAGE_PIPELINES}:${IMAGE_TAG} -f pipelines/Dockerfile_pipelines .
      - name: Push pipeline docker image
        run: docker push ${IMAGE_PIPELINES}:${IMAGE_TAG}
