name: Build kubeflow base image

on:
  push:
    branches:
      - master
    paths:
      - 'base/**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/ca-bundle-oracle-client-base
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-ca-bundle-oracle-client-base:
    name: Build base image with oracle client and ca-bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build kubeflow base docker image
        run: docker build -t ${IMAGE}:${IMAGE_TAG} -f base/Dockerfile.caBundle.base .
      - name: Push kubeflow base docker image
        run: docker push ${IMAGE}:${IMAGE_TAG}

  update-tags:
    name: Update base image tag in dependent jupyterlab and jupyterhub dockerfiles
    runs-on: ubuntu-latest
    needs: build-ca-bundle-oracle-client-base
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Edit Dockerfiles
        run: |
          sed -i "s~.*$IMAGE.*~FROM $IMAGE:$IMAGE_TAG~g" notebooks/jupyterlab/base/Dockerfile.jupyterlab.base
          sed -i "s~.*$IMAGE.*~FROM $IMAGE:$IMAGE_TAG~g" notebooks/jupyterhub/Dockerfile.jupyterhub
      - name: Commit to repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: "Updated base image tag in Dockerfile.jupyterlab.base and Dockerfile.jupyterhub"
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git checkout master
          git add notebooks/
          git diff --quiet && git diff --staged --quiet || (git commit -m "$COMMIT_MSG"; git push origin master)
