name: Build kubeflow jupyterlab base image

on:
  push:
    branches:
      - master
    paths:
      - 'notebooks/jupyterlab/base/**'
      - '.github/workflows/push_jupyterlab_base.yml'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/kubeflow-dataverk-jupyterlab-base
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-jupyterlab-base-image:
    name: Build jupyterlab docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build jupyterlab base docker image
        run: docker build -t ${IMAGE}:${IMAGE_TAG} -f notebooks/jupyterlab/base/Dockerfile.jupyterlab.base .
      - name: Push jupyterlab base docker image
        run: docker push ${IMAGE}:${IMAGE_TAG}

  update-tags:
    name: Update image tag in dependent jupyterlab dockerfile
    runs-on: ubuntu-latest
    needs: build-jupyterlab-base-image
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Edit Dockerfiles
      run: |
        sed -i "s~.*$IMAGE.*~FROM $IMAGE:$IMAGE_TAG~g" notebooks/jupyterlab/kubeflow/Dockerfile.jupyterlab
    - name: Commit to repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MSG: "Updated base image tag in Dockerfile.jupyterlab"
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "$GITHUB_ACTOR"
        git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git checkout master
        git add notebooks/
        git diff --quiet && git diff --staged --quiet || (git pull origin master; git commit -m "$COMMIT_MSG"; git push origin master)
